### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by dollannn** [WaterChick/CRewardR#2]
After running for about 12h (I have automatic restarts every 24h) my server became quite unresponsive and at the same time the plugin spat out an error message for java heap space. My hosting is currently offline so I am unable to give you any logs at this moment, if you need some, tag me and I'll provide them when I have access to them.

**Comment by WaterChick** [comment]
Any log would be great. The error message would be the best.

**Comment by WaterChick** [comment]
I am sure this has something to do with the MySQL, as I said it's new so i am sorry for any complications.

**Comment by dollannn** [comment]
I am too lazy to find the log but here are the tick durations for opening the GUI, presumably caused by the plugin fetching data from the db every time you open it, I'm not an expert at these things but I believe it is possible to optimize it?
![2022-11-24_00 36 36](https://user-images.githubusercontent.com/50216897/203663981-2dd34cd7-610b-4f43-b0ab-e6853852182b.png)

**Comment by WaterChick** [comment]
It is possible, I am currently working on the Database optimiziation, GUI optimization is done.
